### ISSUE TITLE
Should Reflex.match execute on resize?

### ISSUE THREAD

**Issue by giuseppeg** [jxnblk/reflexbox#33] opened 2016-08-04 15:29 UTC
Correct me if I am wrong but right now `Reflex.match` is invoked only on `componentDidMount` and `componentWillReceiveProps`. Shouldn't it run on "resize" too (`mql.addListener`) or do you use `context` for this?

**Comment by BryanARivera** [comment] 2016-08-05 22:58
Is this why the breakpoints only change on browser refresh and not on browser window resize?

The latter does seem to be the standard and correct thing to do. 

Can this be fixed quickly?

**Comment by gerwinbrunner** [comment] 2016-08-09 18:11
I see the same behavior. Even in the sample the resize does not change trigger the the wrap for example. Any reason why this is not done automatically?

**Comment by jxnblk** [comment] 2016-08-10 17:05
This is a duplicate of #10 – for performance reasons, each component doesn't add an event listener for window resize, instead you can add a single listener higher up in the component tree and force render if matchMedia changes. This gives the end user more flexibility in how to handle window resizing.

That said, I'm looking into making Reflexbox work with [react-media-context](https://github.com/jxnblk/react-media-context) and other solutions

**Closed by jxnblk** 2016-08-10 17:05 UTC

**Comment by giuseppeg** [comment] 2016-08-10 19:46
cool, that's what I thought – thank you for clarifying!

fwiw/fyi you don't need to add event listeners for window resize.
You can use 
```javascript
window.matchMedia(mq).addListener(cb)
```

Example http://codepen.io/giuseppegurgone/pen/XKorVY?editors=0010

**Comment by jxnblk** [comment] 2016-08-11 17:52
@giuseppeg wow! have to admit that I didn't know about the matchMedia addListener method. thanks!
